name: EchoTrace CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Python syntax check
        run: |
          python -m compileall .

      - name: EchoTrace project build check
        run: |
          echo Running EchoTrace system checks...
          python EchoTrace-Windows-Security-Visualizer.py --help || echo Skipping GUI check (headless)

      - name: Final message
        run: echo ✅ CI workflow completed for EchoTrace!

